preload = /home/dayr4n/.config/hypr/wallpapers/0anime1.jpg
wallpaper = DP-2,/home/dayr4n/.config/hypr/wallpapers/0anime1.jpg
wallpaper = DP-3,/home/dayr4n/.config/hypr/wallpapers/0anime1.jpg
splash = false
