[manager]
cwd = { fg = "#e8182b", bold = true }
hovered = { fg = "#0a0a0a", bg = "#e8182b", bold = true }
border_style = { fg = "#3a0000" }

[status]
mode_normal = { fg = "#0a0a0a", bg = "#e8182b", bold = true }
mode_select = { fg = "#0a0a0a", bg = "#ff9500", bold = true }
mode_unset  = { fg = "#0a0a0a", bg = "#8b0000", bold = true }

[input]
border = { fg = "#e8182b" }
title  = { fg = "#cc1122", bold = true }
value  = { fg = "#d0d0d0" }

[select]
border   = { fg = "#e8182b" }
active   = { fg = "#e8182b", bold = true }
inactive = { fg = "#444444" }

[which]
cand = { fg = "#e8182b" }
rest = { fg = "#555555" }
desc = { fg = "#888888" }

[help]
on      = { fg = "#e8182b", bold = true }
exec    = { fg = "#cc2222" }
desc    = { fg = "#888888" }
hovered = { bg = "#1a0000", bold = true }
footer  = { fg = "#555555" }
