[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "nvim" }
]
play = [
  { run = 'mpv "$@"', orphan = true, desc = "mpv" }
]
open = [
  { run = 'xdg-open "$@"', orphan = true, desc = "open" }
]

[open]
rules = [
  { mime = "text/*",          use = ["edit", "open"] },
  { mime = "application/json", use = ["edit", "open"] },
  { mime = "image/*",         use = ["open"] },
  { mime = "video/*",         use = ["play", "open"] },
  { mime = "audio/*",         use = ["play", "open"] },
  { mime = "*",               use = ["open", "edit"] },
]
